# -*- coding: utf-8 -*-
"""Laboratorio_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14FwTS0tMJi3zOFtMHqVJ8Eisql-YMHdd

##Laboratorio 2 - Fisica computacional 2
"""

!pip install fitter --quiet

#Librerias
!pip install --upgrade numpy scipy
import re
import warnings

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats

"""#Parte 1"""

URL_EURUSD = ("https://raw.githubusercontent.com/hernansalinas/"
              "Curso_aprendizaje_estadistico/main/datasets/"
              "Pandas_data_historical_dataEURUSD.csv")

# index_col=0 descarta la columna 'Unnamed: 0' (índice guardado al exportar el csv)
eurusd = pd.read_csv(URL_EURUSD, index_col=0, parse_dates=["time"])

print("Dimensiones del dataset:", eurusd.shape)

eurusd = eurusd.set_index("time") # Definimos como indice time
eurusd = eurusd.sort_index()   # garantizamos orden cronológico

print("Tipo de índice:", type(eurusd.index).__name__) #Verificamos el indice
print("Fecha inicial :", eurusd.index.min())
print("Fecha final   :", eurusd.index.max())
eurusd.head()

eurusd.info() #Informacion sobre el dataset

# Estadística descriptiva de todas las columnas numéricas
eurusd.describe()

nulos_por_columna = eurusd.isnull().sum() #Pero antes en .info ya habiamos visto que no hay nulos, igual miramos
print("Valores nulos por columna:")
print(nulos_por_columna)
print()
print("nulos en el DataFrame:", eurusd.isnull().sum().sum())
print("¿Hay algún NaN?", eurusd.isna().any().any())

#5)Utilizamos la notacion de Pacal Case
def a_pascal_case(nombre):
    palabras = re.split(r"[_\s]+", nombre)
    return "".join(p[:1].upper() + p[1:] for p in palabras)

eurusd = eurusd.rename(columns=a_pascal_case)
eurusd.index.name = "Time"

print("Columnas en PascalCase:")
print(list(eurusd.columns))
eurusd.head()

eurusd = eurusd.set_index('Time')
eurusd.index = pd.to_datetime(eurusd.index)
print("Tipo de índice después de la corrección:", type(eurusd.index).__name__)

# Solo usamos el precio de cierre
precio = eurusd[["Close"]].copy()
precio.head()

#Visualizamos el precio de cierre en la serie de tiempo
precio = eurusd[["Close"]].copy()

plt.figure(figsize=(12, 5))
plt.plot(precio.index, precio["Close"], linewidth=1.2)
plt.title("EUR/USD — precio de cierre horario (jul 2022 – may 2023)")
plt.xlabel("Tiempo")
plt.ylabel("Precio de cierre")
plt.tight_layout()
plt.show()

#Diferencia de precio
precio["DiffPrice"] = precio["Close"].diff()
precio.head() #Verificamos que tenga df tenga las dos columnas que nos piden

print("NaN generados por diff():", precio["DiffPrice"].isna().sum())

# Serie limpia que usaremos para el ajuste
diff_precio = precio["DiffPrice"].dropna()
print("Número de datos para el ajuste:", len(diff_precio))
diff_precio.describe()

plt.figure(figsize=(10, 5))
plt.hist(diff_precio, bins=100, color="#3D7BD6", edgecolor="white", linewidth=0.4)
plt.title("Histograma de la diferencia horaria del precio de cierre")
plt.xlabel("DiffPrice  USD por EUR]")
plt.ylabel("Frecuencia")
plt.tight_layout()
plt.show()

# Estadísticos de forma nos anticipan qué familia de distribuciones puede servir
print(f"Media      : {diff_precio.mean(): .6f}")
print(f"Mediana    : {diff_precio.median(): .6f}")
print(f"Desv. est. : {diff_precio.std(): .6f}")
print(f"Asimetría  : {stats.skew(diff_precio): .4f}")
print(f"Curtosis   : {stats.kurtosis(diff_precio): .4f}   (0 = normal)")

from fitter import Fitter, get_common_distributions, get_distributions

datos = diff_precio.values   #Lo escribimos como arreglo de numpy

lista_distribuciones = [
    "norm",       # sugeridas en el enunciado
    "gamma",
    "lognorm",
    "beta",
    "burr",
    "laplace",    # De las sugeridas ene l ejerccioso solo se ajusta norm, entonces debido a la cortusisis se ponene estas
    "t",
    "cauchy",
    "logistic",
    "hypsecant",
]

ajuste = Fitter(datos, distributions=lista_distribuciones)
ajuste.fit()

# las 5 mejores según el error cuadrático de suma
resumen = ajuste.summary(Nbest=5)
plt.tight_layout()
plt.show()
resumen

mejor = ajuste.get_best(method="sumsquare_error")

nombre_mejor = list(mejor.keys())[0]
parametros_mejor = mejor[nombre_mejor]

print("Mejor distribución según sumsquare_error:", nombre_mejor)
print("Parámetros ajustados:")
for k, v in parametros_mejor.items():
    print(f"   {k} = {v:.8f}")

print("Parámetros de la distribución beta:", ajuste.fitted_param["beta"])
print("Parámetros de la distribución norm:", ajuste.fitted_param["norm"])

distribucion = getattr(stats, nombre_mejor)
parametros = ajuste.fitted_param[nombre_mejor]

x = np.linspace(diff_precio.min(), diff_precio.max(), 1000)
pdf_mejor = distribucion.pdf(x, *parametros)
pdf_normal = stats.norm.pdf(x, *stats.norm.fit(datos))

plt.figure(figsize=(10, 5.5))
plt.hist(diff_precio, bins=120, density=True, color="#C9D6E8",
         edgecolor="white", linewidth=0.3, label="Datos (densidad)")
plt.plot(x, pdf_mejor, linewidth=2,
         label=f"Mejor ajuste: {nombre_mejor}")
plt.plot(x, pdf_normal, linewidth=2, linestyle="--",
         label="Normal")
plt.title("DiffPrice: histograma y distribuciones ajustadas")
plt.xlabel("DiffPrice")
plt.ylabel("Densidad de probabilidad")
plt.legend()
plt.tight_layout()
plt.show()

#Ahora nos quedamos con los datos del 2023
precio_2023 = precio.loc["2023"].copy()

print("Registros en 2023:", len(precio_2023))
print("Desde:", precio_2023.index.min(), " hasta:", precio_2023.index.max())
precio_2023.head()

plt.figure(figsize=(12, 5))
plt.plot(precio_2023.index, precio_2023["Close"], linewidth=1.2)
plt.title("EUR/USD — precio de cierre horario durante 2023")
plt.xlabel("Tiempo")
plt.ylabel("Precio de cierre")
plt.tight_layout()
plt.show()

"""##sacamos los datos de la periodicidad deseada"""

promedio_15d = precio_2023.groupby(pd.Grouper(freq="15D")).mean()
promedio_15d

promedio_semanal = precio_2023.groupby(pd.Grouper(freq="W")).mean()
promedio_semanal

promedio_mensual = precio_2023.groupby(pd.Grouper(freq="MS")).mean()
promedio_mensual

# Comparación gráfica de las tres agregaciones sobre la serie horaria
plt.figure(figsize=(12, 6))
plt.plot(precio_2023.index, precio_2023["Close"], color="#C9D6E8",
         linewidth=1, label="Horario")
plt.plot(promedio_semanal.index, promedio_semanal["Close"],
         linewidth=2, marker="o", markersize=5, label="Promedio semanal")
plt.plot(promedio_15d.index, promedio_15d["Close"],
         linewidth=2, marker="s", markersize=6, label="Promedio 15 días")
plt.plot(promedio_mensual.index, promedio_mensual["Close"],
         linewidth=2, marker="^", markersize=8, label="Promedio mensual")
plt.title("EUR/USD 2023 — precio de cierre y promedios a distintas periodicidades")
plt.xlabel("Tiempo")
plt.ylabel("Precio de cierre")
plt.legend()
plt.tight_layout()
plt.show()

"""La segmentacion semanal recupera mejor el comportamiento de la serie de tiempo"""

grupos_mensuales = precio_2023.groupby(pd.Grouper(freq="MS"))

# Primero inspeccionamos qué contiene cada grupo
for nombre, grupo in grupos_mensuales:
    print(f"{nombre.strftime('%Y-%m')}  tiene {len(grupo)} registros")

# Guardamos los grupos que no estén vacíos para graficarlos
meses = [(nombre, grupo) for nombre, grupo in grupos_mensuales if len(grupo) > 0]

n_meses = len(meses)
n_columnas = 3
n_filas = int(np.ceil(n_meses / n_columnas))

fig, ejes = plt.subplots(n_filas, n_columnas, figsize=(14, 4 * n_filas))
ejes = np.array(ejes).flatten()

for i, (nombre, grupo) in enumerate(meses):
    datos_mes = grupo["DiffPrice"].dropna()
    ejes[i].hist(datos_mes, bins=30, color="#3D7BD6",
                 edgecolor="white", linewidth=0.4)
    ejes[i].set_title(f"{nombre.strftime('%B %Y')}  (n = {len(datos_mes)})")
    ejes[i].set_xlabel("DiffPrice")
    ejes[i].set_ylabel("Frecuencia")

# Apagamos los ejes sobrantes de la grilla
for j in range(n_meses, len(ejes)):
    ejes[j].axis("off")

fig.suptitle("Distribución mensual de DiffPrice durante 2023", y=1.01, fontsize=14)
plt.tight_layout()
plt.show()

"""#Analisis de datos con Pandas"""

URL_WDBC = ("https://archive.ics.uci.edu/ml/machine-learning-databases/"
            "breast-cancer-wisconsin/wdbc.data")

rasgos = ["radius", "texture", "perimeter", "area", "smoothness",
          "compactness", "concavity", "concave_points", "symmetry",
          "fractal_dimension"]

# Orden real del archivo: los 10 rasgos con sufijo 1, luego con 2, luego con 3
nombres_columnas = ["id", "diagnosis"] + [f"{r}{i}" for i in (1, 2, 3) for r in rasgos]
cancer = pd.read_csv(URL_WDBC, header=None, names=nombres_columnas)

#Renombramos en formato PascalCase
cancer = cancer.rename(columns=a_pascal_case)

"""##Utilizamos los metodos para obtener informacion de Dataframe

`head()`, `tail()`, `describe()` e `info()`
"""

cancer.head()

cancer.tail()

cancer.describe()

cancer.info()

#Contamos los nulos
nulos = cancer.isnull().sum()
print("Valores nulos por columna :")
print(nulos[nulos > 0] if (nulos > 0).any() else "No hay nulos")
print()
print("Nulos totales:", cancer.isnull().sum().sum())

"""Este dataset está no tiene nulos, pero si aparecieran valores faltantes la estrategia
dependería del tipo de variable y de la cantidad de datos perdidos:

1. Para pocos faltantes (< 5 %) en variables numéricas: imputar con la mediana
   de la columna, que es robusta frente a los outliers que sí tiene este dataset, en esos casos la mediana es mas adecuada que la media.

2. Si hay Muchos faltantes en una columna (> 40 %):eliminar la columna, pues la
   imputación introduciría más ruido que información.

"""

#Identificamos los valores unicos
print("Valores únicos:", cancer["Diagnosis"].unique())
print()
print("Conteo por etiqueta:")
print(cancer["Diagnosis"].value_counts())
print()
print("Proporción:")
print((cancer["Diagnosis"].value_counts(normalize=True) * 100).round(2))

plt.figure(figsize=(7, 4.5))
sns.countplot(data=cancer, x="Diagnosis", hue="Diagnosis",
              order=["B", "M"],
              legend=False)

# Etiquetas directas sobre cada barra: la identidad no depende solo del color
for i, etiqueta in enumerate(["B", "M"]):
    conteo = (cancer["Diagnosis"] == etiqueta).sum()
    plt.text(i, conteo + 5, str(conteo), ha="center", fontsize=11)

plt.title("Número de casos por diagnóstico (B = benigno, M = maligno)")
plt.xlabel("Diagnóstico")
plt.ylabel("Número de casos")
plt.ylim(0, cancer["Diagnosis"].value_counts().max() * 1.12)
plt.tight_layout()
plt.show()

"""El dataset está moderadamente desbalanceado con un 63 %  de benignos y un 37 % de malignos."""

#Le asignamos valores numericos a Beningno (0) y Malingo (1)
cancer["DiagnosisNumeric"] = cancer["Diagnosis"].map({"B": 0, "M": 1})

""" Normalizamos cada columna respecto a su media y desviación estándar utilizando la fórmula:  
   `(x - mean(x)) / std(x)`
"""

#Normalizamos cada columna respecto a su media y su desviacion estandar

columnas_caracteristicas = [c for c in cancer.columns
                            if c not in ("Diagnosis", "DiagnosisNumeric")]

caracteristicas = cancer[columnas_caracteristicas]
cancer_norm = (caracteristicas - caracteristicas.mean()) / caracteristicas.std()

# Conservamos las etiquetas junto a los datos normalizados
cancer_norm["Diagnosis"] = cancer["Diagnosis"]

cancer_norm.head()

# la media es cero y la desviacion estandar debe ser uno
comprobacion = pd.DataFrame({
    "Media": cancer_norm[columnas_caracteristicas].mean(),
    "DesvEst": cancer_norm[columnas_caracteristicas].std(),
})
comprobacion.round(6).head(10)

# La regex toma solo las letras iniciales, descartando el dígito final
for ejemplo in ["Radius1", "Radius2", "ConcavePoints3", "FractalDimension3"]:
    print(f"{ejemplo:20s} -> {re.match(r'^[a-zA-Z_]+', ejemplo).group(0)}")

#  Agrupamos  caracteristicas familiares en familias
familias = {}
for columna in columnas_caracteristicas:
    base = re.match(r"^[a-zA-Z_]+", columna).group(0)
    familias.setdefault(base, []).append(columna)

for base, columnas in familias.items():
    print(f"{base:20s} -> {columnas}")

# Promedio de cada familia; el nombre resultante es Base + 'Mean'
cancer_promedios = pd.DataFrame(index=cancer.index)

for base, columnas in familias.items():
    cancer_promedios[base + "Mean"] = cancer[columnas].mean(axis=1)

cancer_promedios["Diagnosis"] = cancer["Diagnosis"]

print("Columnas resultantes:", list(cancer_promedios.columns))
cancer_promedios.head()

# Promedio de cada familia separado por diagnóstico
cancer_promedios.groupby("Diagnosis").mean().round(3)

#Veamos el radio medio en el vaso Benigno y Maligno
radio_benigno = cancer_promedios.loc[cancer_promedios["Diagnosis"] == "B", "RadiusMean"]
radio_maligno = cancer_promedios.loc[cancer_promedios["Diagnosis"] == "M", "RadiusMean"]

plt.figure(figsize=(10, 5.5))
plt.hist(radio_benigno, bins=30, alpha=0.65,
         edgecolor="white", linewidth=0.5, label="B — Benigno")
plt.hist(radio_maligno, bins=30, alpha=0.65,
         edgecolor="white", linewidth=0.5, label="M — Maligno")
plt.title("Distribución de RadiusMean según el diagnóstico")
plt.xlabel("RadiusMean")
plt.ylabel("Frecuencia")
plt.legend()
plt.tight_layout()
plt.show()

print(f"RadiusMean promedio  |  Benigno: {radio_benigno.mean():.3f}"
      f"   Maligno: {radio_maligno.mean():.3f}")

"""Los tumores malignos tienen un radio claramente mayor, las distribuciones se
solapan poco, así que el radio medio es una variable con buen poder de diferenciacion
"""

# Normalizamos también la tabla de promedios por familia
columnas_promedio = [c for c in cancer_promedios.columns if c != "Diagnosis"]
promedios_norm = ((cancer_promedios[columnas_promedio]
                   - cancer_promedios[columnas_promedio].mean())
                  / cancer_promedios[columnas_promedio].std())
promedios_norm["Diagnosis"] = cancer_promedios["Diagnosis"]

# Utulizamos las caracteristicas del enunciado
columnas_violin = ["RadiusMean", "TextureMean", "PerimeterMean", "AreaMean",
                   "SmoothnessMean", "CompactnessMean", "ConcavityMean",
                   "ConcavePointsMean", "Symmetry3", "FractalDimension3"]

# Las ocho primeras salen de los promedios; las dos últimas del dataset original
tabla_violin = promedios_norm[columnas_violin[:8] + ["Diagnosis"]].copy()
tabla_violin["Symmetry3"] = cancer_norm["Symmetry3"]
tabla_violin["FractalDimension3"] = cancer_norm["FractalDimension3"]

tabla_violin.head()

"""##Grafico tipo violin"""

datos_largos = pd.melt(tabla_violin, id_vars="Diagnosis",
                       var_name="Caracteristica", value_name="Valor")

plt.figure(figsize=(14, 6.5))
sns.violinplot(x="Caracteristica", y="Valor", hue="Diagnosis",
               data=datos_largos, split=True, inner="quart",
               hue_order=["B", "M"],
               palette={"B": "#E8833A", "M": "#3D7BD6"})
plt.xticks(rotation=45, ha="right")
plt.title("Distribución de las características normalizadas según el diagnóstico")
plt.xlabel("")
plt.ylabel("Valor normalizado (z)")
plt.legend(title="Diagnóstico")
plt.tight_layout()
plt.show()

"""En `RadiusMean`, `PerimeterMean`, `AreaMean`,
`ConcavityMean` y `ConcavePointsMean` los dos violines están claramente
desplazados uno respecto del otro, por lo tanto tendremos una buena separación entre clases. En
`SmoothnessMean`, `Symmetry3` y `FractalDimension3` se superponen casi por
completo, por tanto, aportan poca información de diferenciacion por sí solas.

##Outliers
"""

cancer_promedios.boxplot(column="RadiusMean", by="Diagnosis",
                         sym="k.", figsize=(10, 5))
plt.title("RadiusMean por diagnóstico")
plt.suptitle("")          # quita el título automático de pandas
plt.xlabel("Diagnóstico")
plt.ylabel("RadiusMean")
plt.tight_layout()
plt.show()

"""Los valores fuera del rango [Q1 - 1.5 * IQR, Q3 + 1.5 * IQR] se consideran outliers."""

Q1 = cancer_promedios["RadiusMean"].quantile(0.25)
Q3 = cancer_promedios["RadiusMean"].quantile(0.75)
IQR = Q3 - Q1

limite_inferior = Q1 - 1.5 * IQR
limite_superior = Q3 + 1.5 * IQR

print(f"Q1  = {Q1:.4f}")
print(f"Q3  = {Q3:.4f}")
print(f"IQR = {IQR:.4f}")
print(f"Rango aceptado: [{limite_inferior:.4f}, {limite_superior:.4f}]")

mascara_outliers = ((cancer_promedios["RadiusMean"] < limite_inferior) |
                    (cancer_promedios["RadiusMean"] > limite_superior))

# Eliminamos los outliers
cancer_sin_outliers = cancer_promedios[~mascara_outliers].copy()

# Gráfico de la distribución de RadiusMean solo para los datos sin outliers
plt.figure(figsize=(7, 5))
sns.boxplot(data=cancer_sin_outliers, x="Diagnosis", y="RadiusMean",
            hue="Diagnosis", order=["B", "M"], legend=False,
            palette={"B": "#E8833A", "M": "#3D7BD6"})
plt.title("Distribución de RadiusMean (sin outliers)")
plt.xlabel("Diagnóstico")
plt.ylabel("RadiusMean")
plt.tight_layout()
plt.show()

# Correlación entre las 10 familias promediadas (matriz legible)
matriz_correlacion = cancer_promedios.drop(columns="Diagnosis").corr()

"""##Matriz de correlacion"""

#Primero visualizamos el de las familias promediadas
plt.figure(figsize=(10, 8))
sns.heatmap(matriz_correlacion, annot=True, fmt=".2f",
            cmap="RdBu_r", center=0, vmin=-1, vmax=1,
            square=True, linewidths=0.5, cbar_kws={"label": "Correlación de Pearson"})
plt.title("Matriz de correlación")
plt.tight_layout()
plt.show()

# Matriz completa con las 30 características originales del DataSet
plt.figure(figsize=(14, 11))
sns.heatmap(cancer[columnas_caracteristicas].corr(),
            cmap="RdBu_r", center=0, vmin=-1, vmax=1,
            square=True, linewidths=0.2,
            cbar_kws={"label": "Correlación de Pearson"})
plt.title("Matriz de correlación — las 30 características originales")
plt.tight_layout()
plt.show()

"""Con esto vemos cuales son las caracteristicas mas relacionadas con el diagnostico. Se dejan en la siguinte lista por que en este caso me parece dificil visualizar este heatmap"""

correlacion_con_diagnostico = (cancer[columnas_caracteristicas + ["DiagnosisNumeric"]]
                               .corr()["DiagnosisNumeric"]
                               .drop("DiagnosisNumeric")
                               .sort_values(ascending=False))

print("Las 10 características más correlacionadas con un diagnóstico maligno:")
print(correlacion_con_diagnostico.head(10).round(3))

"""##Grafico adicional
Podemos hacer un grafico de sispersion entre las variables corelacionadas que identificamos anteriormente y  ver si es posible separarlas, similar a lo que haciamos en el dataset de pinguinos
"""

plt.figure(figsize=(8.5, 6))
for etiqueta, color, nombre in [("B", "#E8833A", "Benigno"),
                                ("M", "#3D7BD6" , "Maligno")]:
    subconjunto = cancer_promedios[cancer_promedios["Diagnosis"] == etiqueta]
    plt.scatter(subconjunto["RadiusMean"], subconjunto["ConcavePointsMean"],
                s=28, alpha=0.7, color=color, edgecolor="white",
                linewidth=0.6, label=nombre)

plt.title("RadiusMean vs. ConcavePointsMean")
plt.xlabel("RadiusMean")
plt.ylabel("ConcavePointsMean")
plt.legend(title="Diagnóstico")
plt.tight_layout()
plt.show()